api:
  kid: w6n58bqw60075492
  key: "sE/u;u~A>y#eny;ESY9ybEse6U8A`aLA;E)ehE#uXy6Yty!y" # must be surrounded by a double quotes
mobile:
  prefix: mobile
  skin_prefix: default
layout: # to view
  skin_prefix: default # default skin prefix
  required: [ jquery ] # must be list! not string
  side_location: left  # possible values left or right
  # dashboard_ver: 2 # 1 for static widgets, 2 dynamic widgets - obsolete
  ## list of required remote scripts
  # http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js
  # http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js
  # http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js
  # http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/themes/smoothness/jquery-ui.css
  remote:
    proto: http # possible values remote (http,https) or local - local uses scripts from the static/cdn folder 
    scripts:
      jquery:
        version: 1.10.2
        file: jquery.min.js
        url: ajax.googleapis.com/ajax/libs/jquery/
      jquery-validate: 
        version: 1.11.1
        file: jquery.validate.min.js
        url: ajax.aspnetcdn.com/ajax/jquery.validate/
  local_scripts:
    - vendor/jquery.jgrowl-min.js
    - vendor/jquery.sprintf.min.js
    - vendor/jquery.cookie-min.js
    - vendor/jsrender.min.js
    - vendor/jquery.periodic-min.js
    - vendor/raphael-min.js
    - vendor/jquery.placeholder.min.js
    - vendor/jquery.selectBox.min.js
    - vendor/jquery.complexify-min.js
    - vendor/jquery.blockUI-min.js
    - vendor/jquery.stickytableheaders.min.js
    - lib/help-tips.js 
    - lib/jsr.utils.js
    - lib/form_helpers.js
    - lib/sys_helpers.js
    - lib/user_tree.js
    - lib/view.js
    - lib/api2.js
    - global.functions.js
 
  local_css: 
    - jquery.jgrowl.css
    - jquery.complexify.css
    - jquery.selectBox.css 

menu:
  top:
  - title: Dashboard
    href: 
    class: ihome
    acl: 3
  - title: Nodes
    href: nodes
    class: ihv
    acl: 1
  - title: Virtual Machines
    href: vms
    class: ivm
    acl: 3
  - title: Templates
    href: ostmpl
    class: itpl
    acl: 3
  - title: Users
    href: users
    class: iuser
    acl: 2
  - title: Events
    href: events
    class: ievents
    acl: 3
  - title: Settings
    href: config
    class: iconf
    acl: 3
  - title: Help
    href: help
    class: ihelp
    acl: 3
menu2:
  - title: Dashboard
    href: 
    class: ihome
    acl: 3
  - title: Nodes
    href: nodes
    class: ihv
    acl: 1
  - title: Resources
    href: resources
    class: ifolder
    acl: 3
    submenu:
      - title: Virtual Machines
        href: vms
        class: ivm
        acl: 3
      - title: Templates
        href: ostmpl
        class: itpl
        acl: 3
      - title: Users
        href: users
        class: iuser
        acl: 2
  - title: Events
    href: events
    class: ievents
    acl: 3
  - title: Misc
    href: misc
    class: ifolder
    acl: 3
    submenu:
      - title: Tickets Management
        href: issues
        class: iissue
        acl: 3
      # - title: Reports
        # href: repors
        # class: ivm
        # acl: 3
      # - title: DNS Management
        # href: dns
        # class: ivm
        # acl: 3
      # - title: Firewall Management
        # href: fw
        # class: ifw
        # acl: 3
  - title: Settings
    href: config
    class: iconf
    acl: 3
  - title: Help
    href: help
    class: ihelp
    acl: 3
